In [191]:
#1. Given matrices 𝑨𝑨 ∈ R4×2 and 𝑩𝑩 ∈ R4×2, compute the following using Python Programming:

import numpy as np

A = np.array([[22,43], [12, 60], [23, 14], [10, 16]])
B = np.array([[2, 3], [1, 0], [2, 4], [1, 6]])

a = np.dot(A, B.T)
b = A + B
c = A - B
print('a = ', a)
print('b = ', b)
print('c = ', c)

a =  [[173  22 216 280]
 [204  12 264 372]
 [ 88  23 102 107]
 [ 68  10  84 106]]
b =  [[24 46]
 [13 60]
 [25 18]
 [11 22]]
c =  [[20 40]
 [11 60]
 [21 10]
 [ 9 10]]


In [219]:
#2.For the above matrices 𝑨 and 𝑩, compute their Frobenius norms (You cannot use the Python built-in function).

def Frobeniusfunc(A):
    F = 0
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            F += np.square(A[i][j])
#             print(A[i][j])
    return np.sqrt(F)
print('Frobenius norms A =', Frobeniusfunc(A))
print('Frobenius norms B =', Frobeniusfunc(B))


Frobenius norms A = 84.60496439334987
Frobenius norms B = 8.426149773176359


In [250]:
#3.Load the data “KFold.xlsx” and perform 5-fold cross-validation, then compute the average accuracy. 
#Assume the accuracy from the first fold to the fifth fold respectively is 90%, 80%, 75%, 82%, and 95%. 
 
import pandas as pd
import numpy as np
import time

names = ['Sample','var1','var2','var3','var4','var5','var6','var7','var8']
data = pd.read_excel('KFoldCV.xlsx', names = names)
A = [90, 80, 75, 82, 95]

class KFold:
    def __init__(self,n_folds,shuffle):
        self.n_folds = n_folds
        self.shuffle = shuffle
    def split(self,data):
        #Each fold is then used a validation set once while the k - 1 remaining fold form the training set.
        #The first n % n_folds folds have size n // n_folds + 1, other folds have size n // n_folds.
        n = len(data)
        remain = len(data) % self.n_folds
        x = np.arange(n)
        if self.shuffle == True:
            np.random.shuffle(x)
        for i in range (0, self.n_folds):
            start = 0
            end = 0
            if i < remain:
                start = (n // self.n_folds + 1) * (i)
                end = start + (n // self.n_folds + 1) 
            else:
                start = (n // self.n_folds + 1) * remain + (n // self.n_folds) * (i - remain)
                end = start + (n // self.n_folds)
            temp = np.split(x,[start,end])
            train_index = np.append(temp[0],temp[2])
            test_index = temp[1]
            yield np.sort(train_index), np.sort(test_index)
kf = KFold(n_folds=5,shuffle = True)
count = 0
for train_index, test_index in kf.split(data):
    print("TRAIN:", train_index, "TEST:", test_index)
    print("X_train", data.iloc[train_index][names[1:]])
    print("Y_train", data.iloc[train_index]['Sample'])
    print("X_test", data.iloc[test_index][names[1:]])
    print("Y_test", data.iloc[test_index]['Sample'])
    print("Accurancy: ", A[count], "%")
    count = count + 1
print("Average Accurancy: ", np.average(A), "%")


TRAIN: [ 0  1  4  5  6  8  9 10 11 12 13 14] TEST: [2 3 7]
X_train         var1      var2      var3      var4      var5      var6      var7  \
0   0.814724  0.141886  0.706046  0.489764  0.751267  0.349984  0.075854   
1   0.905792  0.421761  0.031833  0.445586  0.255095  0.196595  0.053950   
4   0.632359  0.959492  0.097132  0.754687  0.890903  0.473289  0.934011   
5   0.097540  0.655741  0.823458  0.276025  0.959291  0.351660  0.129906   
6   0.278498  0.035712  0.694829  0.679703  0.547216  0.830829  0.568824   
8   0.957507  0.933993  0.950222  0.162612  0.149294  0.549724  0.011902   
9   0.964889  0.678735  0.034446  0.118998  0.257508  0.917194  0.337123   
10  0.157613  0.757740  0.438744  0.498364  0.840717  0.285839  0.162182   
11  0.970593  0.743132  0.381558  0.959744  0.254282  0.757200  0.794285   
12  0.957167  0.392227  0.765517  0.340386  0.814285  0.753729  0.311215   
13  0.485376  0.655478  0.795200  0.585268  0.243525  0.380446  0.528533   
14  0.800280  0.17118